//
// Code auto-generated by Ray.
// Fri Mar 27 11:09:32 EDT 2026
//
package weston.plugin;
import charlie.card.Card;
import charlie.shoe.Shoe01;
public class BotShoe01 extends Shoe01 {
    @Override
    public void init() {
        cards.clear();
        // Game T0 {5,5,5}: Huey K+6+2 | You 10+5+4 | Dewey 10+10 | Dealer K+7 >> Win{5}, Win{5}, Win{5}
        // Round 1
        // Huey
        cards.add(new Card(Card.KING, Card.Suit.CLUBS));
        // You
        cards.add(new Card(10, Card.Suit.HEARTS));
        // Dewey
        cards.add(new Card(10, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(Card.KING, Card.Suit.CLUBS));
        // Round 2
        // Huey
        cards.add(new Card(6, Card.Suit.DIAMONDS));
        // You
        cards.add(new Card(5, Card.Suit.CLUBS));
        // Dewey
        cards.add(new Card(10, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(7, Card.Suit.CLUBS));
        // Huey
        // Hitting
        cards.add(new Card(2, Card.Suit.HEARTS));
        // You
        // Hitting
        cards.add(new Card(4, Card.Suit.HEARTS));
        // Game T1 {5,5,5}: Huey 5+6+3 | You K+5 | Dewey J+4 | Dealer A+5+5 >> Lose{5}, Lose{5}, Lose{5}
        // Round 1
        // Huey
        cards.add(new Card(5, Card.Suit.HEARTS));
        // You
        cards.add(new Card(Card.KING, Card.Suit.DIAMONDS));
        // Dewey
        cards.add(new Card(Card.JACK, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(Card.ACE, Card.Suit.DIAMONDS));
        // Round 2
        // Huey
        cards.add(new Card(6, Card.Suit.SPADES));
        // You
        cards.add(new Card(5, Card.Suit.SPADES));
        // Dewey
        cards.add(new Card(4, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(5, Card.Suit.DIAMONDS));
        // Huey
        // Hitting
        cards.add(new Card(3, Card.Suit.HEARTS));
        // Dealer
        // Hitting
        cards.add(new Card(5, Card.Suit.DIAMONDS));
        // Game T2 {5,5,5}: Huey 5+3+10 | You K+Q | Dewey 6+4+9 | Dealer 7+7+3 >> Win{5}, Win{5}, Win{5}
        // Round 1
        // Huey
        cards.add(new Card(5, Card.Suit.HEARTS));
        // You
        cards.add(new Card(Card.KING, Card.Suit.CLUBS));
        // Dewey
        cards.add(new Card(6, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(7, Card.Suit.HEARTS));
        // Round 2
        // Huey
        cards.add(new Card(3, Card.Suit.SPADES));
        // You
        cards.add(new Card(Card.QUEEN, Card.Suit.HEARTS));
        // Dewey
        cards.add(new Card(4, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(7, Card.Suit.DIAMONDS));
        // Huey
        // Hitting
        cards.add(new Card(10, Card.Suit.HEARTS));
        // Dewey
        // Hitting
        cards.add(new Card(9, Card.Suit.HEARTS));
        // Dealer
        // Hitting
        cards.add(new Card(3, Card.Suit.HEARTS));
        // Game T3 {5,5,5}: Huey 7+8+J | You 7+Q | Dewey 6+9+4 | Dealer 6+8+4 >> Break{5}, Lose{5}, Win{5}
        // Round 1
        // Huey
        cards.add(new Card(7, Card.Suit.DIAMONDS));
        // You
        cards.add(new Card(7, Card.Suit.HEARTS));
        // Dewey
        cards.add(new Card(6, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(6, Card.Suit.DIAMONDS));
        // Round 2
        // Huey
        cards.add(new Card(8, Card.Suit.DIAMONDS));
        // You
        cards.add(new Card(Card.QUEEN, Card.Suit.HEARTS));
        // Dewey
        cards.add(new Card(9, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(8, Card.Suit.DIAMONDS));
        // Huey
        // Hitting
        cards.add(new Card(Card.JACK, Card.Suit.CLUBS));
        // Dewey
        // Hitting
        cards.add(new Card(4, Card.Suit.CLUBS));
        // Dealer
        // Hitting
        cards.add(new Card(4, Card.Suit.DIAMONDS));
        // Game T4 {5,5,5}: Huey A+J | You K+A | Dewey 6+2+10 | Dealer 6+4+8 >> Win{5}, Win{5}, Push{5}
        // Round 1
        // Huey
        cards.add(new Card(Card.ACE, Card.Suit.HEARTS));
        // You
        cards.add(new Card(Card.KING, Card.Suit.SPADES));
        // Dewey
        cards.add(new Card(6, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(6, Card.Suit.CLUBS));
        // Round 2
        // Huey
        cards.add(new Card(Card.JACK, Card.Suit.DIAMONDS));
        // You
        cards.add(new Card(Card.ACE, Card.Suit.DIAMONDS));
        // Dewey
        cards.add(new Card(2, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(4, Card.Suit.SPADES));
        // Dewey
        // Hitting
        cards.add(new Card(10, Card.Suit.DIAMONDS));
        // Dealer
        // Hitting
        cards.add(new Card(8, Card.Suit.CLUBS));
        // Game T5 {5,5,5}: Huey 2+2+3+10 | You A+Q | Dewey 6+10+J | Dealer 10+7 >> Push{5}, Win{5}, Break{5}
        // Round 1
        // Huey
        cards.add(new Card(2, Card.Suit.HEARTS));
        // You
        cards.add(new Card(Card.ACE, Card.Suit.SPADES));
        // Dewey
        cards.add(new Card(6, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(10, Card.Suit.DIAMONDS));
        // Round 2
        // Huey
        cards.add(new Card(2, Card.Suit.CLUBS));
        // You
        cards.add(new Card(Card.QUEEN, Card.Suit.DIAMONDS));
        // Dewey
        cards.add(new Card(10, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(7, Card.Suit.DIAMONDS));
        // Huey
        // Hitting
        cards.add(new Card(3, Card.Suit.CLUBS));
        cards.add(new Card(10, Card.Suit.HEARTS));
        // Dewey
        // Hitting
        cards.add(new Card(Card.JACK, Card.Suit.HEARTS));
    }
}
// END generated code
